language: csharp
solution: MBINCompiler.sln
mono: latest
dotnet: 2.2.109
before_install:
    # Set the `python` command to be python 3
    - pyenv install 3.6.3
    - pyenv global 3.6.3
install:
    - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1/
    # Install mkdocs version 1.0.4 because it has a nicer style than the more recent version...
    - python3.6 -m pip install --user pytest requests mkdocs==1.0.4
script:
    - dotnet restore
    - dotnet build -r win-x64 -p:Configuration=Release /nowarn:cs0618
    # Build a linux version for running python tests
    - dotnet restore
    - dotnet build -r ubuntu.16.04-x64 -p:Configuration=Release /nowarn:cs0618
    # cwd: /home/travis/build/monkeyman192/MBINCompiler
    - sudo chmod +x Build/Release/ubuntu.16.04-x64/MBINCompiler.exe
    - sudo chmod +x Build/Release/ubuntu.16.04-x64/MBINCompilerDocs.exe
    # Run the tests
    - python3.6 -m pytest --platform ubuntu.16.04-x64 --tb=no --report
    # Build the docs
    - sudo mono Build/Release/ubuntu.16.04-x64/MBINCompilerDocs.exe CI
    - python3.6 -m mkdocs build -q
    # Disable jekyll builds
    - touch html_docs/site/.nojekyll
    # Set the pre-deploy script to be executable
    - sudo chmod +x ./pre_deploy.sh
    - "echo \"Tag: $TRAVIS_TAG\""

before_deploy:
    # Only want to try and get the version if we have the commit being tagged. Otherwise we can only build docs on tagged builds.
    - ./pre_deploy.sh
    #
    # Set up git user name and tag this commit
    #
    #- export TRAVIS_TAG=v$LIBMBIN_VERSION-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
    #- git config --local user.name "Travis-CI"
    #- git config --local user.email "noreply@email.com"
    #- git tag $TRAVIS_TAG

# see https://docs.travis-ci.com/user/deployment/releases/
deploy:
    provider: releases
    prerelease: true
    name: "${TRAVIS_TAG}"
    body: "${TRAVIS_TAG}"
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file:
        - "Build/Release/libMBIN.dll"
        - "Build/Release/win-x64/MBINCompiler.exe"
        - "report.json"
    on:
        branch: development
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[[:digit:]]"

deploy:
    provider: releases
    prerelease: true
    name: "${TRAVIS_TAG}"
    body: "${TRAVIS_TAG}"
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file:
        - "Build/Release/libMBIN.dll"
        - "Build/Release/win-x64/MBINCompiler.exe"
        - "report.json"
    on:
        branch: master
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[[:digit:]]"

# Deploy the docs
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: "html_docs/site"
    on:
        branch: development
        # deploy the docs when the commit message starts with [doc]
        condition: commit_message =~ ^(\[doc\] )(.*)
